    "addi %[add_cnt], %[add_cnt], 4\n\t"
"addi t1, x0, 0\n\t" 
"addi t2, x0, 1\n\t" 
"addi t3, x0, 1\n\t" 
"addi t4, x0, 2\n\t" 

    "addi %[others_cnt], %[others_cnt], 2\n\t"
"fcvt.s.wu f1, t2\n\t" 
"fcvt.s.wu f2, t3\n\t" 

"Loop_pi:\n\t"
        "addi %[others_cnt], %[others_cnt], 1\n\t"
    "beq t1, %[N], Exit_pi\n\t" 
        "addi %[others_cnt], %[others_cnt], 3\n\t"
        "addi %[add_cnt], %[add_cnt], 1\n\t"
        "addi %[fdiv_cnt], %[fdiv_cnt], 1\n\t"
    "fcvt.s.wu f1, t3\n\t" 
    "addi t1, t1, 1\n\t" 
    
    "fdiv.s f1, f1, f2\n\t" 
    
    "rem t2, t1, t4\n\t" 
    "beq t2, x0, Even_pi\n\t" 
        "addi %[others_cnt], %[others_cnt], 1\n\t"
    "jal x0, Odd_pi\n\t" 

"Even_pi:\n\t"
        "addi %[fsub_cnt], %[fsub_cnt], 1\n\t"
        "addi %[fadd_cnt], %[fadd_cnt], 1\n\t"
        "addi %[others_cnt], %[others_cnt], 2\n\t"
    "fsub.s %[pi], %[pi], f1\n\t" 
    "fcvt.s.wu f1, t4\n\t" 
    "fadd.s f2, f2, f1\n\t" 
    "jal x0, Loop_pi\n\t" 

"Odd_pi:\n\t"
        "addi %[fadd_cnt], %[fadd_cnt], 2\n\t"
        "addi %[others_cnt], %[others_cnt], 2\n\t"
    "fadd.s %[pi], %[pi], f1\n\t" 
    "fcvt.s.wu f1, t4\n\t" 
    "fadd.s f2, f2, f1\n\t" 
    "jal x0, Loop_pi\n\t" 

"Exit_pi:\n\t"